* good to know
** deploying
 Username: RVCICT
Password: Rvcict1

To confirm your account, install the latest jitsu: 

        sudo npm install jitsu -g 

and then run: 

        jitsu users confirm rvcict f7ad5bad-6cb8-4a55-9b14-d463a050f8af 

This will allow you to deploy applications with: 

        jitsu deploy 
** cdn: cloudfront  
** email sending:
mandrill.com  
mailchimp.com
mailgun.com
** loosely coupled:
http://somajs.github.io/somajs/site/
** emacs setup
Use nodejs-minor mode. Do a C x,v to compile a node file and see the
output in another window
** Use filemonitor to execute js, or bash processes on file changes
Need to install filemonitor module with npm install filemonitor

** responsive images
Resize images to proper size then include with height=auto and
max-width=100%
http://bjorn.wikkeling.com/115/pure-css-responsive-images-yes-javascript.html
** mind the url with hashbang routing urls:
   href: 'index.html#!/home'
   it's  #!/route following the main page (index.html in this case)

** resizing images:
Install imagemagick then
mogrify -resize x450 *.jpg
mogrify -resize x1000 *.jpg
to resize all images in dir
and:
mogrify -quality 80 *.jpg
to compress
** recaptcha 
Domain Name: 	michieljoris.com

reCAPTCHA will only work on this domain and subdomains. If you have more than one domain (or a staging server), you can create a new set of keys.
Public Key: 	6LfL6OASAAAAAM6YHDJmCJ-51zXY1TwCL7pL7vW5

Use this in the JavaScript code that is served to your users
Private Key: 	6LfL6OASAAAAAHklMnnQdS4AmZvXuOp1ihgPY7V9

Use this when communicating between your server and our server. Be
sure to keep it a secret.
** editing (inline)
redactor, medium.js , zenpen, ckeditor inline, x-editable,
http://hallojs.org/
http://jhollingworth.github.io/bootstrap-wysihtml5/

* todo
  
** later 
*** search button!!!
*** chat
*** blog   
*** bootstrap tooltips for social buttons
*** learning style quiz
*** prefetch images
   possibly also the html?  image optimization using jpegtran?

    
** now    
*** secure email
  firstdoormail@gmail.con
  dropbox pw +1 

*** clean up css for narrow screen,    
fix up ipad issues
menu won't go away, won't scroll to id tag. 
links on resources page.. 
*** breadcrumbs http://static.googleusercontent.com/external_content/untrusted_dlcp/www.google.com/en//webmasters/docs/search-engine-optimization-starter-guide.pdf
*** get rid of dataclone errorimage of stuctured program in here) 
in pd/trainingplans
    
*** inline editing of content
    
* Contact
Andrea mobile is 0437 870 932 or home p: 3491 3573.


* Questions:
  Resources can be organized better and displayed better.
  I'm trying to make it so that you can add resources yourself and edit
  them.  
 


  
