* good to know
** emacs setup
Use nodejs-minor mode. Do a C x,v to compile a node file and see the
output in another window
** Use filemonitor to execute js, or bash processes on file changes
Need to install filemonitor module with npm install filemonitor

** responsive images
Resize images to proper size then include with height=auto and
max-width=100%

** mind the url with hashbang routing urls:
   href: 'index.html#!/home'
   it's  #!/route following the main page (index.html in this case)

** resizing images:
Install imagemagick then
mogrify -resize x450 *.jpg
to resize all images in dir
and:
mogrify -quality 80 *.jpg
to compress

* todo
** angularjs
   
** search button!!!
** chat
** blog   
** hook up markdown editor with server
** contact us in green door, and on every site
  send message thanks for contacting us etc 
  contact us page
   
** learning style quiz
** bigger door
** clean up css for narrow screen, change menu type   
** bread crumbs
** SEO
** bootstrap tooltips for social buttons
** slider with text sliding in 
*** cslider, index3.html
*** Sequence slider
   
   
   
   The wording for the four rolling images on the home page are:
1. Early Childhood Education and Care training
 
2. First Door mentoring inspires focused students
 
3. Innovative resources to bridge the gap between theory and practice
4. Interactive professional development connecting educators to the National Quality Framework
   
* Email to Andrea:
Bars on either side on every page?
I put all images used in Dropbox
No spaces in image names? Replace with underscore
I can make separate page for the pd pages, with the images big on top
again if you like.


* Contact
 Wednesday 17th or Thursday 18th are our next free day time dates!
I am available for skyping or phoning after 3.30pm each day this week
if you find it easier to talk through any of this. My mobile is 0437
870 932 or home p: 3491 3573.
 

