* good to know
** emacs setup
Use nodejs-minor mode. Do a C x,v to compile a node file and see the
output in another window
** Use filemonitor to execute js, or bash processes on file changes
Need to install filemonitor module with npm install filemonitor

** responsive images
Resize images to proper size then include with height=auto and
max-width=100%

** mind the url with hashbang routing urls:
   href: 'index.html#!/home'
   it's  #!/route following the main page (index.html in this case)

   
** resizing images:
Install imagemagick then
mogrify -resize x450 *.jpg
to resize all images in dir
and:
mogrify -quality 80 *.jpg
to compress


** recaptcha 
Domain Name: 	michieljoris.com

reCAPTCHA will only work on this domain and subdomains. If you have more than one domain (or a staging server), you can create a new set of keys.
Public Key: 	6LfL6OASAAAAAM6YHDJmCJ-51zXY1TwCL7pL7vW5

Use this in the JavaScript code that is served to your users
Private Key: 	6LfL6OASAAAAAHklMnnQdS4AmZvXuOp1ihgPY7V9

Use this when communicating between your server and our server. Be sure to keep it a secret.
* todo
  
** later 
*** search button!!!
*** chat
*** blog   
*** hook up markdown editor with server
    
    
** now    
*** contact us in green door, and on every site
   
*** fix up ipad issues
   menu won't go away, won't scroll to id tag. 
   
*** learning style quiz
*** clean up css for narrow screen, change menu type   
*** SEO
*** slider with text sliding in 
cslider, index3.html
Sequence slider
   
   
*** Do the images on front page have image titles? 
   The wording for the four rolling images on the home page are:
1. Early Childhood Education and Care training
 
2. First Door mentoring inspires focused students
 
3. Innovative resources to bridge the gap between theory and practice
4. Interactive professional development connecting educators to the National Quality Framework
   
   
***  courses and pd  a door with contact us.
    

   
*** Email form:
   Styling 
   send message thanks for contacting us etc 

*** Authentication!!!!

*** Setup nodejitsu
    
*** Links in door, like a menu

*** bootstrap tooltips for social buttons

*** prefetch images
   possibly also the html?  image optimization using jpegtran?

*** fixed sidebar/door

*** dropbox file editor using tinymce
   put youtube descriptions in?  
Website developed by michiel    
    
*** make dropbox-server filemap    
 
Accredited Training Can you please use the three titled images for
each of these courses like the use of images for the professional
development workshops
 
Contact Us menu tab information page
Was expecting that this also gave full details as shown in the dropbox with the door contact box
Each page has a space below the green door with links on the left. What it be good to have a “We’re here to help” message with a contact us link to the contact door here?
Is it necessary to have the are you human check on the contact us page?. I personally feel aggravated by these, so would prefer not to have it on our website.
 
The drop box has the following to be updated:
New images with the image title that were unable to be added
dynamically 
An image called ‘bottom letterhead’ that we use for our
documents. I was wondering if this would be good for on top of the
grey bottom panel 
Are we able to use the door format for the contact
us box where they enter their name, question, and email?  
Professional
development workshop introduction with numbered 1,2,3,4 information
points 
Resource blurbs and new resources for motivation and leadership
and management Pdf of First Door policies and procedure manual. Can
this be viewed only with downloading or copying? Is there a way of
protecting this document on the website from being copied?  Pdf of our
privacy policy The full contact us information to be shown from the
menu tab Contact us
 
Grey bottom panel is to have at this stage:
Privacy policy (link to pdf document)
Also, to check whether bottom letterhead image looks good on top of this?
 
The green door with links
Thanks for fixing the shade of green. It looks much better!
At the moment when I’m on the home page this green door floats up over the images when I start scrolling. The rest of the pages do not do this though.
 
Generic website text font 
Now that we have got into writing lots of
documents we have chosen Century Gothic as our standard text font for
First Door. I am feeling nervous about asking you this but here
goes! - How difficult would it be for you to change the entire text of
the website to Century Gothic? Obviously if this was too time
consuming it would not be reasonable to do this.
 
The learning style quiz is tucked away under resources and then under learning, so it would be good to have this in the green door of links separately
Quiz to know your preferred learning style
 
About Us
Under ‘Our Student approach’ the first three bullet points should all be the same.
    
* Contact
Andrea mobile is 0437 870 932 or home p: 3491 3573.

* Questions:
Designed by???

