* good to know
** emacs setup
Use nodejs-minor mode. Do a C x,v to compile a node file and see the
output in another window
** Use filemonitor to execute js, or bash processes on file changes
Need to install filemonitor module with npm install filemonitor

** responsive images
Resize images to proper size then include with height=auto and
max-width=100%

** mind the url with hashbang routing urls:
   href: 'index.html#!/home'
   it's  #!/route following the main page (index.html in this case)

** resizing images:
Install imagemagick then
mogrify -resize x450 *.jpg
to resize all images in dir
and:
mogrify -quality 80 *.jpg
to compress

* todo
  
** later 
*** search button!!!
*** chat
*** blog   
*** hook up markdown editor with server
    
    
** now    
*** contact us in green door, and on every site
   send message thanks for contacting us etc 
   contact us page
    
   
*** fix up ipad issues
   menu won't go away, won't scroll to id tag. 
   
*** learning style quiz
*** bigger door
*** clean up css for narrow screen, change menu type   
*** bread crumbs
*** SEO
*** bootstrap tooltips for social buttons
*** slider with text sliding in 
*** cslider, index3.html
*** Sequence slider
   
   
*** Do the images on front page have image titles? 
   The wording for the four rolling images on the home page are:
1. Early Childhood Education and Care training
 
2. First Door mentoring inspires focused students
 
3. Innovative resources to bridge the gap between theory and practice
4. Interactive professional development connecting educators to the National Quality Framework
   
   
***  courses and pd  a door with contact us.

*** Links in door on other pages.


*** Door bigger, text to the right

    
*** Resources> door will be menu, with submenus that open, and content on the right.

*** Our people in aboutus, people boxes on left.
    
*** make sure email form is safe!!! 
no dangerous html, and spam protected, so some kind of captcha..
    

*** Privacy policy

*** Try slogan underneath slideshow.
*** Cache or preload the pages and images somehow!!!    
preload views!!!   
   Otherwise scrolling doesn't quite get there the first time!!! 
    

   
*** Email form:
Clear after sending. Show Sent! dialog.
    
*** When clicking on link in menu tab, the tab doesn't highlight
    
Black box around tab of page    
   finish it by making a separate function that sets the class to
   active/inactive and leaves the original classes , including anchor tags

*** Authentication!!!!

*** Setup nodejitsu
* Contact
Andrea mobile is 0437 870 932 or home p: 3491 3573.

* Questions:
Designed by???

