* good to know
** deploying
 Username: RVCICT
Password: Rvcict1

To confirm your account, install the latest jitsu: 

        sudo npm install jitsu -g 

and then run: 

        jitsu users confirm rvcict f7ad5bad-6cb8-4a55-9b14-d463a050f8af 

This will allow you to deploy applications with: 

        jitsu deploy 
** cdn: cloudfront  
** email sending:
mandrill.com  
mailchimp.com
mailgun.com
** loosely coupled:
http://somajs.github.io/somajs/site/
** emacs setup
Use nodejs-minor mode. Do a C x,v to compile a node file and see the
output in another window
** Use filemonitor to execute js, or bash processes on file changes
Need to install filemonitor module with npm install filemonitor

** responsive images
Resize images to proper size then include with height=auto and
max-width=100%

** mind the url with hashbang routing urls:
   href: 'index.html#!/home'
   it's  #!/route following the main page (index.html in this case)

   
** resizing images:
Install imagemagick then
mogrify -resize x450 *.jpg
to resize all images in dir
and:
mogrify -quality 80 *.jpg
to compress
** recaptcha 
Domain Name: 	michieljoris.com

reCAPTCHA will only work on this domain and subdomains. If you have more than one domain (or a staging server), you can create a new set of keys.
Public Key: 	6LfL6OASAAAAAM6YHDJmCJ-51zXY1TwCL7pL7vW5

Use this in the JavaScript code that is served to your users
Private Key: 	6LfL6OASAAAAAHklMnnQdS4AmZvXuOp1ihgPY7V9

Use this when communicating between your server and our server. Be
sure to keep it a secret.
** editing (inline)
redactor, medium.js , zenpen, ckeditor inline, x-editable,
http://hallojs.org/
http://jhollingworth.github.io/bootstrap-wysihtml5/

* todo
  
** later 
*** search button!!!
*** chat
*** blog   
*** bootstrap tooltips for social buttons
*** learning style quiz
*** prefetch images
   possibly also the html?  image optimization using jpegtran?

    
** now    
*** secure email
  firstdoormail@gmail.con
dropbox pw +1 

*** clean up css for narrow screen,    
fix up ipad issues
 menu won't go away, won't scroll to id tag. 
 
links on resources page.. 
*** SEO
***** add sitemap
    http://www.sitemaps.org/protocol.html
   
***** make the site crawlable
Which means serve static pages generated by a headless browser. ok
then..
https://developers.google.com/webmasters/ajax-crawling/docs/specification
https://developers.google.com/webmasters/ajax-crawling/docs/html-snapshot
From wikipedia:
The leading search engines, such as Google, Bing and Yahoo!, use
crawlers to find pages for their algorithmic search results. Pages
that are linked from other search engine indexed pages do not need to
be submitted because they are found automatically. Some search
engines, notably Yahoo!, operate a paid submission service that
guarantee crawling for either a set fee or cost per click.[30] Such
programs usually guarantee inclusion in the database, but do not
guarantee specific ranking within the search results.[31] Two major
directories, the Yahoo Directory and the Open Directory Project both
require manual submission and human editorial review.[32] Google
offers Google Webmaster Tools, for which an XML Sitemap feed can be
created and submitted for free to ensure that all pages are found,
especially pages that are not discoverable by automatically following
links.[33]
http://www.yearofmoo.com/2012/11/angularjs-and-seo.html
https://github.com/deanmao/node-chimera
https://github.com/steeve/angular-seo
http://www.marketingpilgrim.com/7-minute-seo-guide
http://static.googleusercontent.com/external_content/untrusted_dlcp/www.google.com/en//webmasters/docs/search-engine-optimization-starter-guide.pdf

*** breadcrumbs http://static.googleusercontent.com/external_content/untrusted_dlcp/www.google.com/en//webmasters/docs/search-engine-optimization-starter-guide.pdf

*** get rid of dataclone errorimage of stuctured program in here) 
in pd/trainingplans
    
    
* Contact
Andrea mobile is 0437 870 932 or home p: 3491 3573.


* Questions:
  Resources can be organized better and displayed better.
  I'm trying to make it so that you can add resources yourself and edit
  them.  
 


  The accredited training course ‘Diploma for Children’s Services’ set
by the ASQA has changed completed last month and is now ‘Diploma of
Early Childhood Education and Care’. This has meant a completely
different course of units, and has required us to change our course
guide etc. These changes need to be updated on the website to replace
the old Diploma name to the new name in the door links under
accredited training, course guide and course unit structure jpg
image. 

The link to accredited training course fees will also need
updating. It’s great that I am able to change the main text, but we
are reliant on you to update these other areas.  

We now have a phone number that also needs to be updated on the
website top header. It would be great to have Phone us (in green same
colour and size as Contact us) and 3103 2336 in same size but in
charcoal grey underneath. Could this please be positioned and aligned
to the left of Contact us and the social media icons?  

Once we have achieved accreditation as a Registered Training
Organisation we will need to insert an accredited training logo in
between First Door’s logo and the ‘Phone us’ in the top header as
well.
  
Hi Andrea,

I updated the course title in the menu and on the door, and have replaced the course guide and course unit structure jpg image.

The training course fees are not as a jpg but as a text. I've forgotten the password for the firstdoor dropbox so I can't edit it myself right now.

I'll put the Phone us tomorrow, you mean to the left of connect with us, not contact us?

I also fixed the spacing of the bottom bar.

Michiel

  
