* good to know
** emacs setup
Use nodejs-minor mode. Do a C x,v to compile a node file and see the
output in another window
** Use filemonitor to execute js, or bash processes on file changes
Need to install filemonitor module with npm install filemonitor

** responsive images
Resize images to proper size then include with height=auto and
max-width=100%

** mind the url with hashbang routing urls:
   href: 'index.html#!/home'
   it's  #!/route following the main page (index.html in this case)

   
** resizing images:
Install imagemagick then
mogrify -resize x450 *.jpg
to resize all images in dir
and:
mogrify -quality 80 *.jpg
to compress


** recaptcha 
Domain Name: 	michieljoris.com

reCAPTCHA will only work on this domain and subdomains. If you have more than one domain (or a staging server), you can create a new set of keys.
Public Key: 	6LfL6OASAAAAAM6YHDJmCJ-51zXY1TwCL7pL7vW5

Use this in the JavaScript code that is served to your users
Private Key: 	6LfL6OASAAAAAHklMnnQdS4AmZvXuOp1ihgPY7V9

Use this when communicating between your server and our server. Be sure to keep it a secret.
* todo
  
** later 
*** search button!!!
*** chat
*** blog   
*** hook up markdown editor with server
    
    
** now    
*** contact us in green door, and on every site
   
*** fix up ipad issues
   menu won't go away, won't scroll to id tag. 
   
*** learning style quiz
*** clean up css for narrow screen, change menu type   
*** SEO
*** slider with text sliding in 
cslider, index3.html
Sequence slider
   
   
*** Do the images on front page have image titles? 
   The wording for the four rolling images on the home page are:
1. Early Childhood Education and Care training
 
2. First Door mentoring inspires focused students
 
3. Innovative resources to bridge the gap between theory and practice
4. Interactive professional development connecting educators to the National Quality Framework
   
   
***  courses and pd  a door with contact us.
    

   
*** Email form:
   Styling 
   send message thanks for contacting us etc 

*** Authentication!!!!

*** Setup nodejitsu
    
*** Links in door, like a menu

*** bootstrap tooltips for social buttons

*** prefetch images
   possibly also the html?  image optimization using jpegtran?

*** fixed sidebar/door

*** dropbox file editor using tinymce
   put youtube descriptions in?  
Website developed by michiel    
    
    
    
    
* Contact
Andrea mobile is 0437 870 932 or home p: 3491 3573.

* Questions:
Designed by???

