* good to know
** emacs setup
Use nodejs-minor mode. Do a C x,v to compile a node file and see the
output in another window
** Use filemonitor to execute js, or bash processes on file changes
Need to install filemonitor module with npm install filemonitor

** responsive images
Resize images to proper size then include with height=auto and
max-width=100%

** mind the url with hashbang routing urls:
   href: 'index.html#!/home'
   it's  #!/route following the main page (index.html in this case)

   
** resizing images:
Install imagemagick then
mogrify -resize x450 *.jpg
to resize all images in dir
and:
mogrify -quality 80 *.jpg
to compress
** recaptcha 
Domain Name: 	michieljoris.com

reCAPTCHA will only work on this domain and subdomains. If you have more than one domain (or a staging server), you can create a new set of keys.
Public Key: 	6LfL6OASAAAAAM6YHDJmCJ-51zXY1TwCL7pL7vW5

Use this in the JavaScript code that is served to your users
Private Key: 	6LfL6OASAAAAAHklMnnQdS4AmZvXuOp1ihgPY7V9

Use this when communicating between your server and our server. Be sure to keep it a secret.
* todo
  
** later 
*** search button!!!
*** chat
*** blog   
*** hook up markdown editor with server
    
*** bootstrap tooltips for social buttons
*** learning style quiz
*** prefetch images
   possibly also the html?  image optimization using jpegtran?


*** letterhead on top or bottom
   
    
** now    
   
*** leftside panel/door
**** Are we able to use the door format for the contact
us box where they enter their name, question, and email?  
**** The learning style quiz is tucked away under resources and then under learning,
 so it would be good to have this in the green door of links separately

 


**** Facebook like right bottom image

**** Pd fees as link to separate page.

**** email bank account detailss 
**** format resources wells
resources title on top.
title links to article.
**** make sure index.html works


*** clean up css for narrow screen,    
fix up ipad issues
 menu won't go away, won't scroll to id tag. 
 
links on resources page.. 
*** SEO
   
*** breadcrumbs 
    
    
* Contact
Andrea mobile is 0437 870 932 or home p: 3491 3573.


* Questions:
  Resources can be organized better and displayed better.
  I'm trying to make it so that you can add resources yourself and edit
  them.  
 


